function model = forward(c, varargin)
  options = Options(varargin{:});

  switch lower(options.model)
  case 'observed'
    dieCount  = c.observations.dieCount;
    timeIndex = c.observations.timeIndex;
  case 'complete'
    dieCount  = c.system.wafer.dieCount;
    timeIndex = [];
  otherwise
    assert(false);
  end

  model = ForwardModel( ...
    'floorplan', c.system.floorplan, ...
    'config',    c.temperature.configuration, ...
    'line',      c.temperature.line, ...
    'leakage',   c.leakage, ...
    'dieCount',  dieCount, ...
    'timeIndex', timeIndex, ...
    'Pdyn',      c.power.Pdyn);
end
