function model = forward(c, varargin)
  options = Options(varargin{:});

  switch lower(options.model)
  case 'observed'
    dieIndex  = c.observations.dieIndex;
    timeIndex = c.observations.timeIndex;
  case 'complete'
    dieIndex  = [];
    timeIndex = [];
  otherwise
    assert(false);
  end

  model = ForwardModel( ...
    'floorplan', c.system.floorplan, ...
    'config',    c.temperature.configuration, ...
    'line',      c.temperature.line, ...
    'dieIndex',  dieIndex, ...
    'timeIndex', timeIndex, ...
    'leakage',   c.leakage, ...
    'process',   c.process, ...
    'Pdyn',      c.power.Pdyn);
end
