function s = substitute(c, m)
  hs = HotSpot.Surrogate('floorplan', c.floorplan, ...
    'config', c.hotspotConfig, 'line', c.hotspotLine);

  s = hs.compute(c.Pdyn, 'leakage', c.leakage, 'process', c.process, ...
    'spaceMeasurementIndex', m.spaceMeasurementIndex, ...
    'timeMeasurementIndex', m.timeMeasurementIndex, ...
    'surrogateOptions', c.surrogateOptions);
end
