function surrogate = substitute(c, m)
  filename = File.temporal(sprintf('Surrogate_%s.mat', ...
    DataHash({ c.power.Pdyn, Utils.toString(c.leakage.model), ...
      Utils.toString(c.process.model), c.surrogate.method, ...
      m.spaceMeasurementIndex, m.timeMeasurementIndex })));

  if File.exist(filename)
    fprintf('Surrogate: using cached data in "%s"...\n', filename);
    load(filename);
  else
    fprintf('Surrogate: construction...\n');

    hs = HotSpot.Surrogate('floorplan', c.system.floorplan, ...
      'config', c.temperature.configuration, 'line', c.temperature.line);

    time = tic;
    surrogate = hs.compute(c.power.Pdyn, ...
      'Lnom', c.process.Lnom, 'Ldev', c.process.Ldev, ...
      'leakage', c.leakage.model, 'process', c.process.model, ...
      'spaceMeasurementIndex', m.spaceMeasurementIndex, ...
      'timeMeasurementIndex', m.timeMeasurementIndex, ...
      'method', c.surrogate.method, ...
      'methodOptions', c.surrogate.options);
    time = toc(time);

    save(filename, 'surrogate', 'time', '-v7.3');
  end

  fprintf('Surrogate: done in %.2f seconds.\n', time);
end
