function surrogate = substitute(c, m)
  filename = File.temporal(sprintf('Surrogate_%s.mat', ...
    DataHash({ c.Pdyn, Utils.toString(c.leakage), ...
      Utils.toString(c.process), c.surrogateMethod, ...
      m.spaceMeasurementIndex, m.timeMeasurementIndex })));

  if File.exist(filename)
    fprintf('Surrogate: using cached data in "%s"...\n', filename);
    load(filename);
  else
    fprintf('Surrogate: construction...\n');

    hs = HotSpot.Surrogate('floorplan', c.floorplan, ...
      'config', c.hotspotConfig, 'line', c.hotspotLine);

    time = tic;
    surrogate = hs.compute(c.Pdyn, ...
      'Lnom', c.Lnom, 'Ldev', c.Ldev, ...
      'leakage', c.leakage, 'process', c.process, ...
      'spaceMeasurementIndex', m.spaceMeasurementIndex, ...
      'timeMeasurementIndex', m.timeMeasurementIndex, ...
      'method', c.surrogateMethod, ...
      'methodOptions', c.surrogateOptions);
    time = toc(time);

    save(filename, 'surrogate', 'time', '-v7.3');
  end

  fprintf('Surrogate: done in %.2f seconds.\n', time);
end
